const BASE=[
 ['バーガー','マクドナルド','mcdonalds.co.jp'],['バーガー','ケンタッキー','kfc.co.jp'],['バーガー','モス','mos.jp'],['バーガー','バーガーキング','burgerking.co.jp'],['スイーツ・カフェ','ミスド','misterdonut.jp'],['寿司','スシロー','akindo-sushiro.co.jp'],['寿司','はま寿司','hama-sushi.co.jp'],['寿司','くら寿司','kurasushi.co.jp'],['丼・定食','松屋','matsuyafoods.co.jp'],['丼・定食','松のや','matsuyafoods.co.jp'],['丼・定食','かつや','arclandservice.co.jp/katsuya'],['ピザ','ドミノピザ','dominos.jp'],['ピザ','ピザハット','pizzahut.jp'],['ピザ','ピザーラ','pizza-la.co.jp'],['スイーツ・カフェ','スターバックス','starbucks.co.jp'],['カレー','ココイチ','ichibanya.co.jp'],['麺','丸亀製麺','marugame.com'],['スイーツ・カフェ','31アイス','31ice.co.jp'],['弁当','ほっともっと','hottomotto.com'],['丼・定食','すき家','sukiya.jp'],['丼・定食','吉野家','yoshinoya.com']
]
const UA={'user-agent':'Mozilla/5.0 (compatible; LimitedMenuFinder/1.0)','accept-language':'ja-JP,ja;q=0.9'}
const text=s=>(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim()
const meta=(h,p)=>{const r=new RegExp(`<meta[^>]+(?:property|name)=["']${p}["'][^>]+content=["']([^"']+)["']|<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${p}["']`,'i').exec(h);return r&&(r[1]||r[2])}
function date(t){let m=t.match(/(20\d{2})[年\/.-]\s*(\d{1,2})[月\/.-]\s*(\d{1,2})日?/);if(m)return`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;m=t.match(/(\d{1,2})月\s*(\d{1,2})日/);if(m){const n=new Date(),mo=+m[1];let y=n.getFullYear();if(mo<n.getMonth()-2)y++;return`${y}-${String(mo).padStart(2,'0')}-${m[2].padStart(2,'0')}`}return null}
function extract(h,url,c){const title=text(meta(h,'og:title')||((h.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||''));const desc=text(meta(h,'og:description')||meta(h,'description')||'');const body=text(h).slice(0,60000),all=`${title} ${desc} ${body}`;if(!/(期間限定|新発売|新商品|季節限定|数量限定|限定販売|新登場)/.test(all))return null;const sc=(all.match(/(?:販売|発売|提供|登場|開始)[^。]{0,80}(?:20\d{2}年)?\s*\d{1,2}月\s*\d{1,2}日[^。]{0,30}/)||[])[0]||'';const start=date(sc);if(!start)return null;const ec=(all.match(/(?:販売終了|終了予定|まで)[^。]{0,80}(?:20\d{2}年)?\s*\d{1,2}月\s*\d{1,2}日/)||[])[0]||'';const pm=all.match(/(?:税込(?:価格)?\s*)?[￥¥]?\s?([0-9]{2,4}(?:,[0-9]{3})?)\s*円(?:\s*\(税込\))?/);let image=meta(h,'og:image')||null;try{if(image)image=new URL(image,url).href}catch{}return{store:c[1],category:c[0],title:title.replace(/\s*[|｜].*$/,'').slice(0,120),price:pm?`${pm[1]}円${/税込/.test(pm[0])?'（税込）':''}`:null,image,startDate:start,endDate:date(ec),url}}
function ddgLinks(h,domain){const links=[];for(const m of h.matchAll(/class=["'][^"']*result__a[^"']*["'][^>]+href=["']([^"']+)/gi)){let u=m[1].replace(/&amp;/g,'&');try{const x=new URL(u,'https://duckduckgo.com');u=x.searchParams.get('uddg')||u}catch{}try{u=decodeURIComponent(u)}catch{}if(u.includes(domain.split('/')[0])&&!links.includes(u))links.push(u)}return links}
async function one(c){try{const q=encodeURIComponent(`site:${c[2]} ${c[1]} 期間限定 新商品 発売`),s=await fetch(`https://html.duckduckgo.com/html/?q=${q}`,{headers:UA,signal:AbortSignal.timeout(6500)});if(!s.ok)return[];const links=ddgLinks(await s.text(),c[2]);const out=[];for(const u of links.slice(0,2)){try{const r=await fetch(u,{headers:UA,redirect:'follow',signal:AbortSignal.timeout(5500)});if(!r.ok)continue;const p=extract(await r.text(),r.url,c);if(p)out.push(p)}catch{}}return out}catch{return[]}}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'POST only'});const extras=Array.isArray(req.body?.extraStores)?req.body.extraStores.filter(x=>Array.isArray(x)&&x.length===3&&/^[a-z0-9.-]+(?:\/[a-z0-9_\/-]+)?$/i.test(x[2])):[];const stores=[...BASE,...extras].slice(0,30),results=[];for(let i=0;i<stores.length;i+=5){const batch=await Promise.all(stores.slice(i,i+5).map(one));results.push(...batch.flat())}const seen=new Set(),products=results.filter(p=>p&&p.title&&p.url&&!seen.has(p.url)&&seen.add(p.url)).sort((a,b)=>new Date(b.startDate)-new Date(a.startDate));res.setHeader('Cache-Control','no-store');res.status(200).json({products,updatedAt:new Date().toISOString(),warning:products.length?'':'公式ページから販売開始日まで確認できる商品を取得できませんでした。サイト側の検索制限やページ構造変更の可能性があります。'})}
